### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by joshuaruxpin** [Z3RYX/TagSDK#1]
it says it is missing tagSDk.exe does not exist how do i fix this

**Comment by Z3RYX** [comment]
Sorry to disappoint, but there isn't really anything in this repo worth building.

I abandoned it quite awhile ago without having done much progress on it. The only existing thing in here is a partial level definition. The console app "TagSDK" only has the "Hello World" from the template, so even if you do build and run this, it would do nothing.

Also sorry for the late answer. I didn't expect any issues to pop up on any of my repos, especially not the older ones.
(as for your issue, it sounds more like you're trying to run it without building first, because the .exe can only exist after building it first)
